//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public Benefit()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Benefit_ID { get; set; }
        public string Benefit_Type { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
