//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Divisions = new HashSet<Division>();
        }
    
        public int CID { get; set; }
        public string CName { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Division> Divisions { get; set; }
    }
}
