//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendences = new HashSet<Attendence>();
            this.Promotions = new HashSet<Promotion>();
            this.SalaryHistories = new HashSet<SalaryHistory>();
            this.Transfer_Info = new HashSet<Transfer_Info>();
        }
    
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Maritual_status { get; set; }
        public string Religion { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Home_phone { get; set; }
        public string Present_address { get; set; }
        public string parmanent_address { get; set; }
        public Nullable<int> DID { get; set; }
        public Nullable<int> DesId { get; set; }
        public Nullable<int> SecID { get; set; }
        public Nullable<int> DivID { get; set; }
        public Nullable<int> Benefit_ID { get; set; }
        public Nullable<int> EmployeeType_ID { get; set; }
        public Nullable<int> GID { get; set; }
        public Nullable<double> Gross_Salary { get; set; }
    
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual Benefit Benefit { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Division Division { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<SalaryHistory> SalaryHistories { get; set; }
        public virtual ICollection<Transfer_Info> Transfer_Info { get; set; }
    }
}
