//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int GID { get; set; }
        public string Grade_Name { get; set; }
        public Nullable<int> Grade_Salary { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
