//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryHead
    {
        public int ID { get; set; }
        public string Head_Name { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<bool> Activity { get; set; }
    }
}
