//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryHistory
    {
        public int SalaryHistoryID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<decimal> Basics { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Convences { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
        public Nullable<int> PromotionID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
