//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Info
    {
        public int TransferID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string OldDepartment { get; set; }
        public string NewDepartment { get; set; }
        public string OldDivision { get; set; }
        public string NewDivision { get; set; }
        public string OldSection { get; set; }
        public string NewSection { get; set; }
        public Nullable<System.DateTime> TransferActiveDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Remark { get; set; }
        public string StatusState { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
